//
// File generated by rootcint at Sat Jun 27 17:36:07 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PigsDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PigsDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void PigsGUI_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_PigsGUI(void *p);
   static void deleteArray_PigsGUI(void *p);
   static void destruct_PigsGUI(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PigsGUI*)
   {
      ::PigsGUI *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PigsGUI >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PigsGUI", ::PigsGUI::Class_Version(), "./PigsGUI.h", 36,
                  typeid(::PigsGUI), DefineBehavior(ptr, ptr),
                  &::PigsGUI::Dictionary, isa_proxy, 4,
                  sizeof(::PigsGUI) );
      instance.SetDelete(&delete_PigsGUI);
      instance.SetDeleteArray(&deleteArray_PigsGUI);
      instance.SetDestructor(&destruct_PigsGUI);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PigsGUI*)
   {
      return GenerateInitInstanceLocal((::PigsGUI*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PigsGUI*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void PigsEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_PigsEvent(void *p = 0);
   static void *newArray_PigsEvent(Long_t size, void *p);
   static void delete_PigsEvent(void *p);
   static void deleteArray_PigsEvent(void *p);
   static void destruct_PigsEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PigsEvent*)
   {
      ::PigsEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PigsEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PigsEvent", ::PigsEvent::Class_Version(), "./PigsEvent.h", 15,
                  typeid(::PigsEvent), DefineBehavior(ptr, ptr),
                  &::PigsEvent::Dictionary, isa_proxy, 4,
                  sizeof(::PigsEvent) );
      instance.SetNew(&new_PigsEvent);
      instance.SetNewArray(&newArray_PigsEvent);
      instance.SetDelete(&delete_PigsEvent);
      instance.SetDeleteArray(&deleteArray_PigsEvent);
      instance.SetDestructor(&destruct_PigsEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PigsEvent*)
   {
      return GenerateInitInstanceLocal((::PigsEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PigsEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void PigsStorage_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_PigsStorage(void *p = 0);
   static void *newArray_PigsStorage(Long_t size, void *p);
   static void delete_PigsStorage(void *p);
   static void deleteArray_PigsStorage(void *p);
   static void destruct_PigsStorage(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PigsStorage*)
   {
      ::PigsStorage *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PigsStorage >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PigsStorage", ::PigsStorage::Class_Version(), "./PigsStorage.h", 21,
                  typeid(::PigsStorage), DefineBehavior(ptr, ptr),
                  &::PigsStorage::Dictionary, isa_proxy, 4,
                  sizeof(::PigsStorage) );
      instance.SetNew(&new_PigsStorage);
      instance.SetNewArray(&newArray_PigsStorage);
      instance.SetDelete(&delete_PigsStorage);
      instance.SetDeleteArray(&deleteArray_PigsStorage);
      instance.SetDestructor(&destruct_PigsStorage);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PigsStorage*)
   {
      return GenerateInitInstanceLocal((::PigsStorage*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PigsStorage*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *PigsGUI::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PigsGUI::Class_Name()
{
   return "PigsGUI";
}

//______________________________________________________________________________
const char *PigsGUI::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PigsGUI*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PigsGUI::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PigsGUI*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PigsGUI::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PigsGUI*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PigsGUI::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PigsGUI*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *PigsEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PigsEvent::Class_Name()
{
   return "PigsEvent";
}

//______________________________________________________________________________
const char *PigsEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PigsEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PigsEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PigsEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PigsEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PigsEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PigsEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PigsEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *PigsStorage::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PigsStorage::Class_Name()
{
   return "PigsStorage";
}

//______________________________________________________________________________
const char *PigsStorage::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PigsStorage*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PigsStorage::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PigsStorage*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PigsStorage::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PigsStorage*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PigsStorage::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PigsStorage*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void PigsGUI::Streamer(TBuffer &R__b)
{
   // Stream an object of class PigsGUI.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(PigsGUI::Class(),this);
   } else {
      R__b.WriteClassBuffer(PigsGUI::Class(),this);
   }
}

//______________________________________________________________________________
void PigsGUI::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PigsGUI.
      TClass *R__cl = ::PigsGUI::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMainGUIFrame", &fMainGUIFrame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMainTitle", &fMainTitle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fStartDAQ", &fStartDAQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fStopDAQ", &fStopDAQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fExitDAQ", &fExitDAQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabHolder", &fTabHolder);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCurHistFrame", &fCurHistFrame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLatestHistoCanvas", &fLatestHistoCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cCurrHCanvas", &cCurrHCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHCurrHProgressBar", &fHCurrHProgressBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabHisto", &fTabHisto);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLastNspectra", &fLastNspectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cLastNspectra", &cLastNspectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabConfig", &fTabConfig);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabDT5781", &fTabDT5781);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDTinfo", &fDTinfo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fInitDAQ", &fInitDAQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDisconnectDAQ", &fDisconnectDAQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabAbout", &fTabAbout);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ufont", &ufont);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fColor", &fColor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*uGC", &uGC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "valTitle", (void*)&valTitle);
      R__insp.InspectMember("GCValues_t", (void*)&valTitle, "valTitle.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fAcqThread", &fAcqThread);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*daq", &daq);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*storage", &storage);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ev", &ev);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_PigsGUI(void *p) {
      delete ((::PigsGUI*)p);
   }
   static void deleteArray_PigsGUI(void *p) {
      delete [] ((::PigsGUI*)p);
   }
   static void destruct_PigsGUI(void *p) {
      typedef ::PigsGUI current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::PigsGUI

//______________________________________________________________________________
void PigsStorage::Streamer(TBuffer &R__b)
{
   // Stream an object of class PigsStorage.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(PigsStorage::Class(),this);
   } else {
      R__b.WriteClassBuffer(PigsStorage::Class(),this);
   }
}

//______________________________________________________________________________
void PigsStorage::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PigsStorage.
      TClass *R__cl = ::PigsStorage::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*outf", &outf);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fFileName", &fFileName);
      R__insp.InspectMember(fFileName, "fFileName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*t", &t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*e", &e);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_PigsStorage(void *p) {
      return  p ? new(p) ::PigsStorage : new ::PigsStorage;
   }
   static void *newArray_PigsStorage(Long_t nElements, void *p) {
      return p ? new(p) ::PigsStorage[nElements] : new ::PigsStorage[nElements];
   }
   // Wrapper around operator delete
   static void delete_PigsStorage(void *p) {
      delete ((::PigsStorage*)p);
   }
   static void deleteArray_PigsStorage(void *p) {
      delete [] ((::PigsStorage*)p);
   }
   static void destruct_PigsStorage(void *p) {
      typedef ::PigsStorage current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::PigsStorage

//______________________________________________________________________________
void PigsEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class PigsEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(PigsEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(PigsEvent::Class(),this);
   }
}

//______________________________________________________________________________
void PigsEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PigsEvent.
      TClass *R__cl = ::PigsEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*spectrum", &spectrum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "realTime", &realTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "deadTime", &deadTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "goodCounts", &goodCounts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "totCounts", &totCounts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "countsPerSecond", &countsPerSecond);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_PigsEvent(void *p) {
      return  p ? new(p) ::PigsEvent : new ::PigsEvent;
   }
   static void *newArray_PigsEvent(Long_t nElements, void *p) {
      return p ? new(p) ::PigsEvent[nElements] : new ::PigsEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_PigsEvent(void *p) {
      delete ((::PigsEvent*)p);
   }
   static void deleteArray_PigsEvent(void *p) {
      delete [] ((::PigsEvent*)p);
   }
   static void destruct_PigsEvent(void *p) {
      typedef ::PigsEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::PigsEvent

/********************************************************
* PigsDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePigsDict();

extern "C" void G__set_cpp_environmentPigsDict() {
  G__cpp_reset_tagtablePigsDict();
}
#include <new>
extern "C" int G__cpp_dllrevPigsDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PigsGUI */
static int G__PigsDict_524_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PigsGUI* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new PigsGUI((TGWindow*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) PigsGUI((TGWindow*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PigsDictLN_PigsGUI));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PigsGUI*) G__getstructoffset())->InitDAQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PigsGUI*) G__getstructoffset())->DisconnectDAQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PigsGUI*) G__getstructoffset())->RunSingleAcquisition());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PigsGUI*) G__getstructoffset())->StopAcquisition());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PigsGUI*) G__getstructoffset())->SetProgressBarPosition((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PigsGUI::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsGUI::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PigsGUI::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PigsGUI::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PigsGUI*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsGUI::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PigsGUI::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsGUI::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_524_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PigsGUI::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PigsGUI G__TPigsGUI;
static int G__PigsDict_524_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PigsGUI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PigsGUI*) (soff+(sizeof(PigsGUI)*i)))->~G__TPigsGUI();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PigsGUI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PigsGUI*) (soff))->~G__TPigsGUI();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* PigsEvent */
static int G__PigsDict_841_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PigsEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PigsEvent[n];
     } else {
       p = new((void*) gvp) PigsEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PigsEvent;
     } else {
       p = new((void*) gvp) PigsEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PigsDictLN_PigsEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PigsEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PigsEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PigsEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PigsEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PigsEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_841_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PigsEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PigsDict_841_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PigsEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PigsEvent(*(PigsEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PigsDictLN_PigsEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PigsEvent G__TPigsEvent;
static int G__PigsDict_841_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PigsEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PigsEvent*) (soff+(sizeof(PigsEvent)*i)))->~G__TPigsEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PigsEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PigsEvent*) (soff))->~G__TPigsEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PigsDict_841_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PigsEvent* dest = (PigsEvent*) G__getstructoffset();
   *dest = *(PigsEvent*) libp->para[0].ref;
   const PigsEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* PigsStorage */
static int G__PigsDict_842_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PigsStorage* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new PigsStorage(*((TString*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) PigsStorage(*((TString*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PigsDictLN_PigsStorage));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PigsStorage* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PigsStorage[n];
     } else {
       p = new((void*) gvp) PigsStorage[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PigsStorage;
     } else {
       p = new((void*) gvp) PigsStorage;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PigsDictLN_PigsStorage));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((PigsStorage*) G__getstructoffset())->getE());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((PigsStorage*) G__getstructoffset())->getOutFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((PigsStorage*) G__getstructoffset())->getTree());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((const PigsStorage*) G__getstructoffset())->getOutFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PigsStorage::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsStorage::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PigsStorage::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PigsStorage::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PigsStorage*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsStorage::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PigsStorage::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PigsStorage::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PigsDict_842_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PigsStorage::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PigsDict_842_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PigsStorage* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PigsStorage(*(PigsStorage*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PigsDictLN_PigsStorage));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PigsStorage G__TPigsStorage;
static int G__PigsDict_842_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PigsStorage*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PigsStorage*) (soff+(sizeof(PigsStorage)*i)))->~G__TPigsStorage();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PigsStorage*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PigsStorage*) (soff))->~G__TPigsStorage();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PigsDict_842_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PigsStorage* dest = (PigsStorage*) G__getstructoffset();
   *dest = *(PigsStorage*) libp->para[0].ref;
   const PigsStorage& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PigsGUI */

/* PigsEvent */

/* PigsStorage */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPigsDict {
 public:
  G__Sizep2memfuncPigsDict(): p(&G__Sizep2memfuncPigsDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPigsDict::*p)();
};

size_t G__get_sizep2memfuncPigsDict()
{
  G__Sizep2memfuncPigsDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePigsDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI))) {
     PigsGUI *G__Lderived;
     G__Lderived=(PigsGUI*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI),G__get_linked_tagnum(&G__PigsDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PigsDictLN_PigsEvent))) {
     PigsEvent *G__Lderived;
     G__Lderived=(PigsEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsEvent),G__get_linked_tagnum(&G__PigsDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PigsDictLN_PigsStorage))) {
     PigsStorage *G__Lderived;
     G__Lderived=(PigsStorage*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsStorage),G__get_linked_tagnum(&G__PigsDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePigsDict() {

   /* Setting up typedef entry */
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__PigsDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PigsDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__PigsDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__PigsDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PigsGUI */
static void G__setup_memvarPigsGUI(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI));
   { PigsGUI *p; p=(PigsGUI*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGMainFrame),-1,-1,4,"fMainGUIFrame=",0,"Main GUI window");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGLabel),-1,-1,4,"fMainTitle=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTextButton),-1,-1,4,"fStartDAQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTextButton),-1,-1,4,"fStopDAQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTextButton),-1,-1,4,"fExitDAQ=",0,"buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTab),-1,-1,4,"fTabHolder=",0,"tab widget");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGCompositeFrame),-1,-1,4,"fCurHistFrame=",0,"container of \"CurrentHistogram\"");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TRootEmbeddedCanvas),-1,-1,4,"fLatestHistoCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TCanvas),-1,-1,4,"cCurrHCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGHProgressBar),-1,-1,4,"fHCurrHProgressBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGCompositeFrame),-1,-1,4,"fTabHisto=",0,"container of \"History\"");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TRootEmbeddedCanvas),-1,-1,4,"fLastNspectra=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TCanvas),-1,-1,4,"cLastNspectra=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGCompositeFrame),-1,-1,4,"fTabConfig=",0,"container of \"Config\"");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGCompositeFrame),-1,-1,4,"fTabDT5781=",0,"container of \"DT5781\"");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTextView),-1,-1,4,"fDTinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTextButton),-1,-1,4,"fInitDAQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGTextButton),-1,-1,4,"fDisconnectDAQ=",0,"buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGCompositeFrame),-1,-1,4,"fTabAbout=",0,"container of \"About\"");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGFont),-1,-1,4,"ufont=",0,"will reflect user font changes");
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("ULong_t"),-1,4,"fColor=",0,"Color helper");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TGGC),-1,-1,4,"uGC=",0,"will reflect user GC changes");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PigsDictLN_GCValues_t),-1,-1,4,"valTitle=",0,"graphics context changes");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TThread),-1,-1,4,"fAcqThread=",0,"Acquisition thread");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_PigsDAQ),-1,-1,4,"daq=",0,"DAQ pointer");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_PigsStorage),-1,-1,4,"storage=",0,"Data storage");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_PigsEvent),-1,-1,4,"ev=",0,"Event buffer used to fill the storage");
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,4,"fGUIsizeX=600LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,4,"fGUIsizeY=500LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("int32_t"),-2,4,"fVerbose=1LL",0,"verbosity level settings");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* PigsEvent */
static void G__setup_memvarPigsEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsEvent));
   { PigsEvent *p; p=(PigsEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->spectrum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TH1D),-1,-1,1,"spectrum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->realTime)-(long)(p)),107,0,0,-1,-1,-1,1,"realTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->deadTime)-(long)(p)),107,0,0,-1,-1,-1,1,"deadTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->goodCounts)-(long)(p)),104,0,0,-1,-1,-1,1,"goodCounts=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->totCounts)-(long)(p)),104,0,0,-1,-1,-1,1,"totCounts=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->countsPerSecond)-(long)(p)),100,0,0,-1,-1,-1,1,"countsPerSecond=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* PigsStorage */
static void G__setup_memvarPigsStorage(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsStorage));
   { PigsStorage *p; p=(PigsStorage*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TFile),-1,-1,4,"outf=",0,"Filename to write the tree");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PigsDictLN_TString),-1,-1,4,"fFileName=",0,"Name of the output file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TTree),-1,-1,4,"t=",0,"Tree with measurements");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_PigsEvent),-1,-1,4,"e=",0,"Measurement object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PigsDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPigsDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPigsGUI(void) {
   /* PigsGUI */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsGUI));
   G__memfunc_setup("PigsGUI",632,G__PigsDict_524_0_1, 105, G__get_linked_tagnum(&G__PigsDictLN_PigsGUI), -1, 0, 1, 1, 1, 0, "U 'TGWindow' - 10 - p", "Creates the GUI", (void*) NULL, 0);
   G__memfunc_setup("InitDAQ",618,G__PigsDict_524_0_2, 105, -1, -1, 0, 0, 1, 1, 0, "", "Initialization of the PigsDAQ object, DPP library, DAQ config", (void*) NULL, 0);
   G__memfunc_setup("DisconnectDAQ",1248,G__PigsDict_524_0_3, 105, -1, -1, 0, 0, 1, 1, 0, "", "Ends connection to the DPP library", (void*) NULL, 0);
   G__memfunc_setup("RunSingleAcquisition",2080,G__PigsDict_524_0_4, 105, -1, -1, 0, 0, 1, 1, 0, "", "Runs one acquisition loop", (void*) NULL, 0);
   G__memfunc_setup("StopAcquisition",1583,G__PigsDict_524_0_5, 105, -1, -1, 0, 0, 1, 1, 0, "", "Stops acquisition on channel 0", (void*) NULL, 0);
   G__memfunc_setup("SetProgressBarPosition",2283,G__PigsDict_524_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - fposition", "Set the position of the progress bar", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PigsDict_524_0_7, 85, G__get_linked_tagnum(&G__PigsDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PigsGUI::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PigsDict_524_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsGUI::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PigsDict_524_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PigsGUI::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PigsDict_524_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PigsGUI::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PigsDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PigsDict_524_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PigsDict_524_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsGUI::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PigsDict_524_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PigsGUI::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PigsDict_524_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsGUI::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PigsDict_524_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PigsGUI::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~PigsGUI", 758, G__PigsDict_524_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncPigsEvent(void) {
   /* PigsEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsEvent));
   G__memfunc_setup("PigsEvent",917,G__PigsDict_841_0_1, 105, G__get_linked_tagnum(&G__PigsDictLN_PigsEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PigsDict_841_0_2, 85, G__get_linked_tagnum(&G__PigsDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PigsEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PigsDict_841_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PigsDict_841_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PigsEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PigsDict_841_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PigsEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PigsDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PigsDict_841_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PigsDict_841_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PigsDict_841_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PigsEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PigsDict_841_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PigsDict_841_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PigsEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PigsEvent", 917, G__PigsDict_841_0_14, (int) ('i'), G__get_linked_tagnum(&G__PigsDictLN_PigsEvent), -1, 0, 1, 1, 1, 0, "u 'PigsEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PigsEvent", 1043, G__PigsDict_841_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PigsDict_841_0_16, (int) ('u'), G__get_linked_tagnum(&G__PigsDictLN_PigsEvent), -1, 1, 1, 1, 1, 0, "u 'PigsEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncPigsStorage(void) {
   /* PigsStorage */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PigsDictLN_PigsStorage));
   G__memfunc_setup("PigsStorage",1128,G__PigsDict_842_0_1, 105, G__get_linked_tagnum(&G__PigsDictLN_PigsStorage), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - foutname", "Use this constructor", (void*) NULL, 0);
   G__memfunc_setup("PigsStorage",1128,G__PigsDict_842_0_2, 105, G__get_linked_tagnum(&G__PigsDictLN_PigsStorage), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getE",389,G__PigsDict_842_0_3, 85, G__get_linked_tagnum(&G__PigsDictLN_PigsEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOutFile",1016,G__PigsDict_842_0_4, 85, G__get_linked_tagnum(&G__PigsDictLN_TFile), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTree",720,G__PigsDict_842_0_5, 85, G__get_linked_tagnum(&G__PigsDictLN_TTree), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOutFileName",1401,G__PigsDict_842_0_6, 67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PigsDict_842_0_7, 85, G__get_linked_tagnum(&G__PigsDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PigsStorage::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PigsDict_842_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsStorage::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PigsDict_842_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PigsStorage::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PigsDict_842_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PigsStorage::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PigsDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PigsDict_842_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PigsDict_842_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsStorage::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PigsDict_842_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PigsStorage::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PigsDict_842_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PigsStorage::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PigsDict_842_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PigsStorage::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PigsStorage", 1128, G__PigsDict_842_0_19, (int) ('i'), G__get_linked_tagnum(&G__PigsDictLN_PigsStorage), -1, 0, 1, 1, 1, 0, "u 'PigsStorage' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PigsStorage", 1254, G__PigsDict_842_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PigsDict_842_0_21, (int) ('u'), G__get_linked_tagnum(&G__PigsDictLN_PigsStorage), -1, 1, 1, 1, 1, 0, "u 'PigsStorage' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPigsDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPigsDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPigsDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PigsDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_GCValues_t = { "GCValues_t" , 115 , -1 };
G__linked_taginfo G__PigsDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGGC = { "TGGC" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGFont = { "TGFont" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__PigsDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGHProgressBar = { "TGHProgressBar" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TThread = { "TThread" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TGTextView = { "TGTextView" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_PigsGUI = { "PigsGUI" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_PigsDAQ = { "PigsDAQ" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_PigsEvent = { "PigsEvent" , 99 , -1 };
G__linked_taginfo G__PigsDictLN_PigsStorage = { "PigsStorage" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePigsDict() {
  G__PigsDictLN_TClass.tagnum = -1 ;
  G__PigsDictLN_TBuffer.tagnum = -1 ;
  G__PigsDictLN_TMemberInspector.tagnum = -1 ;
  G__PigsDictLN_TObject.tagnum = -1 ;
  G__PigsDictLN_TString.tagnum = -1 ;
  G__PigsDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PigsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PigsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PigsDictLN_GCValues_t.tagnum = -1 ;
  G__PigsDictLN_TGObject.tagnum = -1 ;
  G__PigsDictLN_TQObject.tagnum = -1 ;
  G__PigsDictLN_TGWindow.tagnum = -1 ;
  G__PigsDictLN_TGGC.tagnum = -1 ;
  G__PigsDictLN_TGFont.tagnum = -1 ;
  G__PigsDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__PigsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PigsDictLN_TGFrame.tagnum = -1 ;
  G__PigsDictLN_TGCompositeFrame.tagnum = -1 ;
  G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__PigsDictLN_TGTextButton.tagnum = -1 ;
  G__PigsDictLN_TGMainFrame.tagnum = -1 ;
  G__PigsDictLN_TCanvas.tagnum = -1 ;
  G__PigsDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__PigsDictLN_TGTab.tagnum = -1 ;
  G__PigsDictLN_TGLabel.tagnum = -1 ;
  G__PigsDictLN_TGHProgressBar.tagnum = -1 ;
  G__PigsDictLN_TThread.tagnum = -1 ;
  G__PigsDictLN_TGTextView.tagnum = -1 ;
  G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__PigsDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PigsDictLN_TFile.tagnum = -1 ;
  G__PigsDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__PigsDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__PigsDictLN_TH1D.tagnum = -1 ;
  G__PigsDictLN_PigsGUI.tagnum = -1 ;
  G__PigsDictLN_PigsDAQ.tagnum = -1 ;
  G__PigsDictLN_TTree.tagnum = -1 ;
  G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__PigsDictLN_PigsEvent.tagnum = -1 ;
  G__PigsDictLN_PigsStorage.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePigsDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TString);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_GCValues_t);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGGC);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGFont);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGHProgressBar);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TThread);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TGTextView);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TH1D);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PigsDictLN_PigsGUI),sizeof(PigsGUI),-1,324608,(char*)NULL,G__setup_memvarPigsGUI,G__setup_memfuncPigsGUI);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_PigsDAQ);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PigsDictLN_PigsEvent),sizeof(PigsEvent),-1,292096,(char*)NULL,G__setup_memvarPigsEvent,G__setup_memfuncPigsEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PigsDictLN_PigsStorage),sizeof(PigsStorage),-1,324864,(char*)NULL,G__setup_memvarPigsStorage,G__setup_memfuncPigsStorage);
}
extern "C" void G__cpp_setupPigsDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPigsDict()");
  G__set_cpp_environmentPigsDict();
  G__cpp_setup_tagtablePigsDict();

  G__cpp_setup_inheritancePigsDict();

  G__cpp_setup_typetablePigsDict();

  G__cpp_setup_memvarPigsDict();

  G__cpp_setup_memfuncPigsDict();
  G__cpp_setup_globalPigsDict();
  G__cpp_setup_funcPigsDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPigsDict();
  return;
}
class G__cpp_setup_initPigsDict {
  public:
    G__cpp_setup_initPigsDict() { G__add_setup_func("PigsDict",(G__incsetup)(&G__cpp_setupPigsDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPigsDict() { G__remove_setup_func("PigsDict"); }
};
G__cpp_setup_initPigsDict G__cpp_setup_initializerPigsDict;

