/********************************************************************
* PigsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PigsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePigsDict();
extern void G__cpp_setup_inheritancePigsDict();
extern void G__cpp_setup_typetablePigsDict();
extern void G__cpp_setup_memvarPigsDict();
extern void G__cpp_setup_globalPigsDict();
extern void G__cpp_setup_memfuncPigsDict();
extern void G__cpp_setup_funcPigsDict();
extern void G__set_cpp_environmentPigsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PigsGUI.h"
#include "PigsStorage.h"
#include "PigsEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PigsDictLN_TClass;
extern G__linked_taginfo G__PigsDictLN_TBuffer;
extern G__linked_taginfo G__PigsDictLN_TMemberInspector;
extern G__linked_taginfo G__PigsDictLN_TObject;
extern G__linked_taginfo G__PigsDictLN_TString;
extern G__linked_taginfo G__PigsDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__PigsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PigsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PigsDictLN_GCValues_t;
extern G__linked_taginfo G__PigsDictLN_TGObject;
extern G__linked_taginfo G__PigsDictLN_TQObject;
extern G__linked_taginfo G__PigsDictLN_TGWindow;
extern G__linked_taginfo G__PigsDictLN_TGGC;
extern G__linked_taginfo G__PigsDictLN_TGFont;
extern G__linked_taginfo G__PigsDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__PigsDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PigsDictLN_TGFrame;
extern G__linked_taginfo G__PigsDictLN_TGCompositeFrame;
extern G__linked_taginfo G__PigsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PigsDictLN_TGTextButton;
extern G__linked_taginfo G__PigsDictLN_TGMainFrame;
extern G__linked_taginfo G__PigsDictLN_TGTab;
extern G__linked_taginfo G__PigsDictLN_TGLabel;
extern G__linked_taginfo G__PigsDictLN_TCanvas;
extern G__linked_taginfo G__PigsDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__PigsDictLN_TGHProgressBar;
extern G__linked_taginfo G__PigsDictLN_TThread;
extern G__linked_taginfo G__PigsDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__PigsDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PigsDictLN_TFile;
extern G__linked_taginfo G__PigsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PigsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PigsDictLN_TH1D;
extern G__linked_taginfo G__PigsDictLN_PigsGUI;
extern G__linked_taginfo G__PigsDictLN_PigsDAQ;
extern G__linked_taginfo G__PigsDictLN_PigsEvent;
extern G__linked_taginfo G__PigsDictLN_TTree;
extern G__linked_taginfo G__PigsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PigsDictLN_PigsStorage;

/* STUB derived class for protected member access */
